### ISSUE TITLE
[Feature request] helm chart 

### ISSUE THREAD

**Issue by StepanKuksenko** [nabsul/k8s-ecr-login-renew#23] opened 2021-08-02 10:17 UTC
what do you think about creating simple helm chart with cronjob/serviceaccount deployment and put it here in /deploy folder and maybe to some public chart museum. 
it would be easier to install your tool, just copy the command from the readme `helm install ....` and thats it.

**Comment by nabsul** [comment] 2021-08-02 18:33
Hi Stephan,

Thanks for your suggestion. I'm happy to discuss, but I'll be honest and admit that I personally am [not a fan of Helm](https://www.linkedin.com/posts/nabsul_i-want-to-like-helm-but-i-just-cant-recommend-activity-6795026678864330752-8tDl). I've found that Help usually causes more trouble than good.

I can think of three reasons for saying no to Helm:

First, adding Helm to automate two `kubectl apply` commands seems like overkill. Running two `apply` commands is much faster than installing helm and then running one helm command. I could also merge the two yaml files into one :-) 

Second, I believe that hiding too much from the developer doesn't always help them. If anything goes wrong or fails, there is more that needs to be debugged to find where the problem is.

And third, adding a Helm chart would add to the work I do maintaining this free open source tool. Especially if it's not adding much benefit, it doesn't make sense to give myself more code to debug/test/maintain.

I think having this in Helm could make sense if it was part of a larger deployment. For example, a chart that deploys nginx ingress, load balancer, cert-manager, and this tool all together.

I still appreciate your feedback, and would be happy to discuss this further. Maybe I'm just not understanding Helm? If I don't hear back from you for a few weeks I'll close this issue.

Thanks again.

**Comment by StepanKuksenko** [comment] 2021-08-03 15:08
thank you for your response
so I agree with each of your reasons.
But I would say one thing: if you make an open-source project, you definitely want people to use it. Having a helm chart will increase the reach of people who will use your application, this is the main reason. 

Use cases:
- in our workflow we helmfile for everything, deploy infra, application etc. so for us it is easier to use helm charts instead of raw manifests;
- on my opinion, it Is easies to take helm chart, examine the values.yaml file, define needed variables and apply it instead of using raw manifests, I sure that there are also people like me ) 
- etc.

Conclusion: you can keep helm chart as well as raw k8s manifests, just to increase amount of people which could use your application.

example my case: I decided to use another solution instead of creating helm chart for your one ) 

anyway, good job. thank you for each line of code you've written here )))

**Comment by nabsul** [comment] 2021-08-03 15:14
Sounds reasonable. I would need to ramp up on Helm because I don't currently use it, so there's no timeline for this.

But if you would like to contribute the chart, that would be cool. I just might have a lot of questions before it gets merged :-)

**Comment by nabsul** [comment] 2022-04-17 14:54
Sorry for the long time silence on this, but that's life :-) 

I am hoping to be able to follow up on this to get it merged... early next month.

**Comment by nabsul** [comment] 2022-09-09 00:58
Thank you all for the push for Helm chart support. I'm still not a huge fan, and I wish there was something better/easier. But I can see its value and the benefit over plain yaml files.

An initial version is now up and running at https://nabsul.github.io/helm (https://nabsul.github.io/helm/index.yaml). I still have a lot of review and cleanup to do on https://github.com/nabsul/k8s-ecr-login-renew/pull/38, but it should be a matter of days, not weeks to get this done.

**Closed** 2023-02-20 21:28 UTC
